version: '3'

services:
  freeswitch-google:
    build:
      context: .
    restart: unless-stopped
    container_name: freeswitch-google
    ports:
      - "5061:5061"
      - "8443:8443"
      - "8080:8080"
    environment:
      - TRUNK_TYPE
      - TRUNK_ACCOUNT
      - TRUNK_PASSWORD
    volumes:
      - ./scratch/usr/local/freeswitch/conf:/usr/local/freeswitch/conf
      - ./credentials:/credentials
      - ./templates:/templates
