version: '3'

services:
  freeswitch-google:
    build:
      context: .
    restart: unless-stopped
    container_name: freeswitch-google
    environment:
      - FREESWITCH_PASSWORD
      - FREESWITCH_SIP_PORT=5080
      - FREESWITCH_DTLS_SIP_PORT=5081
      - FREESWITCH_RTP_START_PORT=25000
      - FREESWITCH_RTP_END_PORT=25020
    ports:
      - "8021:8021"
      - "5080:5080"
      - "5081:5081"
      - "25000-25020:25000-25020"
    volumes:
      - ./credentials:/credentials
